### ISSUE TITLE
Undefined offset on line 640 of idx-api.php

### ISSUE THREAD

**Issue by jdelia** [idxbroker/wordpress-plugin#43] opened 2016-01-12 16:31 UTC
Query Monitor is throwing this notice: 
PHP Error   Count   Location    Call Stack  Component
Notice  Undefined offset: 0 4   wp-content/plugins/idx-broker-platinum/idx/idx-api.php:640  IDX\Idx_Api->platinum_account_type()
IDX\Widgets\Create_Impress_Widgets->__construct()
IDX\Initiate_Plugin->__construct()
eval()
Idx_Broker_Plugin->__construct()    Plugin: idx-broker-platinum

**Comment by antonioortegajr** [comment] 2018-11-19 19:14
This is not showing in the Query Monitor plugin for me. I am unable to reproduce now and this issue may have been addressed in a previous release? Closing until this can reproduced.

**Closed by antonioortegajr** 2018-11-19 19:14 UTC
Labels: bug
