### ISSUE TITLE
PHP Version Check doesn't work

### ISSUE THREAD

**Issue by bhubbard** [idxbroker/wordpress-plugin#3] opened 2015-10-21 21:18 UTC
Per this following Facebook thread:
https://www.facebook.com/groups/idxbrokermastermindgroup/882070538537497/

I installed a fresh version of WordPress on php 5.2.17, along with the IDX Broker plugin. Upon activation I get the following error:
![](https://www.evernote.com/shard/s1/sh/42e0902c-043d-45f4-a827-82e41a9cff78/148ae1247a11a66f/res/bf619d6c-857e-4610-a685-15bf8f2e3cdb/skitch.png?resizeSmall&width=832)

The plugin already has a message and version check:
[Version Check and Message code](https://github.com/idxbroker/wordpress-plugin/blob/master/idx-broker-platinum/idx-broker-platinum.php#L36-L60)

However this check and messaging does not actually check or display when a user activates the plugin. I believe it doesn't check when a user updates the plugin as well.

Useful Resource:
[Best way to abort plugin in case of insufficient PHP Version](http://wordpress.stackexchange.com/questions/76007/best-way-to-abort-plugin-in-case-of-insufficient-php-version)

**Comment by sheparddw** [comment] 2015-10-21 22:47
The issue is actually with the PHP parser for versions less than 5.3. The parser thinks namespaces are a syntax error before the version check has a chance to run.
I have completed a fix that will be released in the next version of the plugin (1.3.0).

**Closed by sheparddw** 2015-10-21 22:47 UTC
