### ISSUE TITLE
Duplicate wrapper if updating page name

### ISSUE THREAD

**Issue by AlphaBlossom** [idxbroker/wordpress-plugin#59] opened 2016-07-07 00:33 UTC
If I go to initial settings (WordPress admin) and have a page name for the global wrapper and click "Update", it creates a duplicate wrapper.

So if I have "Homes" with a slug of "homes" and update with "Homes" still in the field, I'll get another "Homes" wrapper, slug "homes-2".

**Comment by antonioortegajr** [comment] 2018-11-19 19:03
This appears to no longer be the case. This could be because of the change to use custom post types. Closing until this can be reproduced.

**Closed by antonioortegajr** 2018-11-19 19:03 UTC
Labels: bug
